name: clang-format

on: [push, pull_request]

permissions:
  contents: read

jobs:
  check-clang-format:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
        with:
          egress-policy: audit

      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - run: npm install
      - name: check clang-format
        run: |
          git config clangFormat.binary node_modules/.bin/clang-format
          git config clangFormat.style file
          npx check-clang-format
