name: Node.js CI

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read

jobs:
  test:
    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
        operating-system: [ubuntu-latest, windows-2019, macos-latest]

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
        with:
          egress-policy: audit

      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@bea5baf987ba7aa777a8a0b4ace377a21c45c381 # v3.8.0
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install -g cmake-js@6.3.2
      - run: npm install
      - name: Environment Information
        run: npx envinfo
      - name: Run Test
        run: npm test

  nightly-daily-test:
    runs-on: ubuntu-latest
    container: node
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
        with:
          egress-policy: audit

      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - run: npm i -g n && n nightly
      - run: node -p process.versions
      - name: Environment Information
        run: npx envinfo
      - run: npm install -g cmake-js@6.3.2
      - run: npm install
      - name: Environment Information
        run: npx envinfo
      - name: Run Test
        continue-on-error: true
        run: npm test
