name: Build and Deploy the Website

on:
  push:
    branches: [ main ]

permissions:
  contents: write # Pushes to `gh-pages` branch

jobs:
  deploy-website:
    runs-on: ubuntu-latest
    container: node
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
        with:
          persist-credentials: false
      - run: npx envinfo
      - name: Build and Deploy
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          USER: gatsby-deploy-bot <support+actions@github.com>
          NODE_OPTIONS: --openssl-legacy-provider
        working-directory: ./website
        run: |
          npm install
          npx gatsby build --prefix-paths
          npx gh-pages -d public -r https://git:${TOKEN}@github.com/${REPO}.git -u "${USER}"
